/********************************************************************
 * imgLib v0.1.2 09.04.2011
 * Contact me at dev@jstoys.org.ua
 * Site: http://jstoys.org.ua/
 * This copyright notice MUST stay intact for use.
 ********************************************************************/
if(!window.$)var $=function(a){return typeof a=="string"?document.getElementById(a):a};var addEvent=function(){return document.attachEvent?function(a,c,b){a.attachEvent("on"+c,b)}:document.addEventListener?function(a,c,b){a.addEventListener(c,b,!1)}:function(a,c,b){a["on"+c]=b}}(),cancelEvent=function(){return document.attachEvent?function(a){if(!a)return!1;a.returnValue=!1;a.cancelBubble=!0}:document.addEventListener?function(a){if(!a)return!1;a.preventDefault();a.stopPropagation()}:function(){return!1}}();
function fixEvent(a){a=a||window.event;if(a.isFixed)return a;a.isFixed=!0;if(a.pageX==null&&a.clientX!=null){var c=document.documentElement,b=document.body;a.pageX=a.clientX+(c&&c.scrollLeft||b&&b.scrollLeft||0)-(c.clientLeft||0);a.pageY=a.clientY+(c&&c.scrollTop||b&&b.scrollTop||0)-(c.clientTop||0)}if(!a.target&&a.srcElement)a.target=a.srcElement;if(!a.which&&a.button)a.which=a.button&1?1:a.button&2?3:a.button&4?2:0;return a}
function getURIEncPath(a){var c="",b="",d,e;if(a.indexOf("http://")!=-1||a.indexOf("https://")!=-1)c=a.substring(0,a.indexOf("://")+3),a=a.substring(c.length,a.length);c.length>0&&a.indexOf(":")!=-1&&a.indexOf(":")<a.length&&(e=a.indexOf("/",a.indexOf(":")+1),e=e==-1?a.length:e,b=a.substring(0,e),a=a.substring(b.length,a.length));a=a.split("/");d=0;for(e=a.length;d<e;d++)a[d]=encodeURIComponent(a[d]);return c+b+a.join("/")}
function HTMLDecode(a){if(!a)return"";var c=document.createElement("b");c.innerHTML=a;return c.firstChild.data}function getURLArg(a){var a=a||"&",c=window.location.search.substring(1).split(a),b=window.location.href,b=(b.indexOf("#")!=-1?b.substring(b.indexOf("#")+1):"").split(a),a={search:{},hash:{}},d,e;for(e=c.length;e-- >0;)d=c[e].split("="),a.search[d[0]]=a[d[0]]=d[1]||null;for(e=b.length;e-- >0;)d=b[e].split("="),a.hash[d[0]]=a[d[0]]=d[1]||null;return a}
function setLocationHash(a){var c=[],b;for(b in a)b&&c.push(b+"="+a[b]);window.location.hash=c.join("&")}function sprintf(a){var c=arguments,b;for(b=c.length;--b>0;)a=a.replace(RegExp("%"+b,"g"),c[b]);return a}this.JSON||(JSON={parse:function(a){return eval("("+a+")")}});
function getWindowGeometry(){var a,c,b,d,e=window,f=document;if(e.innerWidth)a=e.innerWidth,c=e.innerHeight,b=e.pageXOffset,d=e.pageYOffset;else if(f.documentElement&&f.documentElement.clientWidth)a=f.documentElement.clientWidth,c=f.documentElement.clientHeight,b=f.documentElement.scrollLeft,d=f.documentElement.scrollTop;else if(f.body.clientWidth)a=f.body.clientWidth,c=f.body.clientHeight,b=f.body.scrollLeft,d=f.body.scrollTop;return{width:a,height:c,xOffset:b,yOffset:d}}
function getWindowSize(){var a=getWindowGeometry();return{width:a.width,height:a.height}}function getElPos(a){typeof a=="string"&&(a=$(a));for(var c=0,b=0,d=a.offsetWidth,e=a.offsetHeight;a;)c+=a.offsetTop,b+=a.offsetLeft,a=a.offsetParent;return{top:c,left:b,width:d,height:e}}
function getXHR(){var a,c,b;try{a=new XMLHttpRequest,getXHR=function(){return new XMLHttpRequest}}catch(d){XmlHttpVersions=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.5.0","MSXML2.XMLHTTP.4.0","MSXML2.XMLHTTP.3.0","Msxml2.XMLHTTP","Microsoft.XMLHTTP"];c=0;for(b=XmlHttpVersions.length;c<b&&!a;c++)try{a=new ActiveXObject(XmlHttpVersions[c]),getXHR=function(){return new ActiveXObject(XmlHttpVersions[c])}}catch(e){}}if(a)return a;else alert("can't create XMLHttpRequest object")}
function sendXMLHttpReq(a,c){if(a){var b={mode:"GET",async:!0,contentType:"application/x-www-form-urlencoded",encoding:"UTF-8",parameters:"",onsuccess:null},d=getXHR();extend(b,c||{});b.parameters=b.parameters?b.parameters:b.mode=="POST"?"":null;try{d.open(b.mode,a,b.async);b.mode=="POST"&&(d.setRequestHeader("Content-Type",b.contentType+(b.encoding?"; charset="+b.encoding:"")),d.setRequestHeader("Content-length",b.parameters.length),d.setRequestHeader("Connection","close"));if(typeof b.onsuccess==
"function")d.onreadystatechange=function(){if(d.readyState==4)if(d.status==200)try{b.onsuccess(d)}catch(a){alert("2can't process ajax,"+a.toString())}else alert("3can't process ajax,"+d.statusText)};d.send(b.parameters)}catch(e){alert("1can't process ajax,"+e.toString())}}}
function getCookie(a){var c=document.cookie;a+="=";var b=c.indexOf("; "+a),d;if(b==-1){if(b=c.indexOf(a),b!=0)return null}else b+=2;d=document.cookie.indexOf(";",b);if(d==-1)d=c.length;return decodeURIComponent(c.substring(b+a.length,d))}function setCookie(a,c,b,d){var e=new Date;b?(e.setTime(e.getTime()+b*1E3),b="; expires="+e.toGMTString()):b="";document.cookie=a+"="+encodeURIComponent(c)+b+"; path="+(d?d:"/")}
function setTransparency(a,c){a=$(a);if(typeof a=="object")c=parseInt(c),c<1&&(c*=100),a.filters?a.style.filter=c<100?"alpha(opacity = "+c+")":"":a.style.opacity=c/100}function getAttributes(a){var c={},b,d;if(a.attributes)for(b=a.attributes.length;b-- >0;)d=a.attributes[b],c[d.nodeName]=d.nodeValue;return c}function extend(a,c,b){for(var d in c)if(c.hasOwnProperty(d)||b)typeof c[d]=="object"&&!(c[d]instanceof Array)?extend(a[d]||{},c[d],b):a[d]=c[d];return a}
function toggle(a){a=$(a).style;a.display=a.display!="none"?"none":""}function addClass(a,c){a=$(a);remClass(a,c);var b=a.className.split(" ");b.push(c);a.className=b.join(" ")}function remClass(a,c){var a=$(a),b=a.className.split(" "),d;for(d=b.length;d-- >0;)b[d]==c&&b.splice(d,1);a.className=b.join(" ")}function createElement(a,c){return extend(document.createElement(a),c||{},1)}
function getDateF(a,c){var a=a?new Date(a):new Date,b=[a.getFullYear(),a.getDate(),a.getMonth()+1,a.getHours(),a.getMinutes(),a.getSeconds()],d,e;c>0&&(c=b[1],b[1]=b[2],b[2]=c);d=0;for(e=b.length;d<e;d++)b[d]=b[d].toString().length<2?"0"+b[d].toString():b[d];return[b[0],"/",b[1],"/",b[2]," ",b[3],":",b[4],":",b[5]].join("")}function getHumanSize(a,c){for(var c=c||["b","Kb","Mb","Gb","Tb","Eb"],b=0;a>=1024&&b<c.length;)a/=1024,b++;a%1!=0&&(a=a.toFixed(2));return a+" "+c[b]}
function translateLabels(a){if(typeof a=="object"){var c,b,d;for(c=a.length;c-- >0;)if($(a[c].id))if(b=$(a[c].id),typeof a[c].prop=="object")for(d in a[c].prop)b[d]=HTMLDecode(a[c].prop[d]);else if(typeof a[c].prop=="string")b.innerHTML=HTMLDecode(a[c].prop)}};