/********************************************************************
 * imgLib v0.1.2 09.04.2011
 * Contact me at dev@jstoys.org.ua
 * Site: http://jstoys.org.ua/
 * This copyright notice MUST stay intact for use.
 ********************************************************************/
var imgLib=function(){function kb(a){var b,a=extend({idName:"imgLib",reqURL:"imglib.php",confName:"default",immediateStart:!1,bindKeys:!0,historyNavigation:!0,hashRecheckInterval:0.1,saveState:!0,updateTitle:!0,enableUpload:!0,uploadPath:"/upload/",startDir:i,allowedExt:["jp\u0435g","jpg","gif","png"],maxUploadSize:0,maxUploadFileSize:0,saveInfCookie:"imglibInf",sortType:1,sortOrder:0,maxFileNameLen:30,enableBrowseSubdir:!0,enableFileOperation:!0,enableCreateDir:!0,enableRename:!0,enableDelete:!0,
thmbPath:"",thmbDir:"thmb",tooltipsDelay:400,overlayOpacity:75,tooltipOverlayOpacity:90,dbclickDelay:400,onSelect:void 0,onDblSelect:void 0,onDeselect:void 0,viewType:"thumbnail",messages:{rootPathName:"Root",ajaxLoading:"Loading...",moveToUpDir:"Up",delNonEmptyDir:'Remove not empty folder "%1"?',delFile:'Remove "%1"?',enterNewDirName:"Enter name of new directory:",defaultNewDirName:"New Folder",enterNewNameWOExt:'Enter new name of "%1":\n(file extension is add automatic)',operationFailed:"Operation failed. Error code is %1.",
ajaxIsReguire:"This script reguire browser that support the AJAX tehnology!",noChange:"No change!",newDir:"Create folder",select:"Select",selectThmb:"Select thumbnail",open:"Open",browse:"Browse",copy:"Copy",cut:"Cut",paste:"Paste",del:"Delete",rename:"Rename",reloadDir:"Reload curent directory",fileName:"File name",fileSize:"File size",fileDate:"File date",date:"Date",size:"Size",imageSize:"Image size",view:"View",thumbnail:"Thumbnail",list:"List",table:"Table",search:"Search",enterSearch:"Enter part of file name:",
sort:"Sort",sortByName:"By name",sortBySize:"By size",sortByDate:"By date",upload:"Upload",cancel:"Cancel",writeProtect:"Directory is write protected!",addField:"Add more field",delField:"Delete field",allowExt:"Allowed extension: %1.",maxUploadSize:"Max upload size (total/file): %1/%2.",path:"Path: %1",close:"Close",error:"Error: ",multipleUpload:"Your browser supports multiple selection of files to upload. Try it.",dragAndDropSupport:"Your browser supports easy &quot;drag &amp; drop&quot; files upload. Try it - select file and drag it to browser.",
uploadResult:"Uploaded files: %1. Name(s): %2.",savedAs:"Saved as: %1.",autoCloseForm:"Automatically close the form after upload is finished.",noFileSelected:"No file selected!",dropTargetText:"Drop your files here",speed:"Speed",speedUnit:"/s",timeLeft:"Time left",time:"Time",second:"s",waitInQueue:"Waiting in queue",canceled:"Canceled",abort:"Abort",aborted:"Aborted",tryAgain:"Try again",errorUpload:"Error on upload",errorOnResponse:"Error on response: ",fileType:"File type: ",unknownMime:"unknown",
ec107:"Bad file name.",ec200:"Folder is not writable.",ec500:"Can not get free file name.",ec501:"Illegal file type.",ec502:"File size limit exceeded.",ec503:"Some error when move upload file.",ec504:"No free space left.",ec506:"Local and remote file sizes do not match.",fileSizeDim:["b","Kb","Mb","Gb","Tb","Eb"]},contextMenuItems:[]},a||{});extend(ra,a);sa=a.idName;u=a.reqURL;Y=a.confName;Ma=!!a.immediateStart;w=!!a.bindKeys;ia=!!a.historyNavigation;Na=a.hashRecheckInterval;Z=!!a.saveState;ta=!!a.enableUpload;
E=a.uploadPath;i=a.startDir||i;Oa=a.allowedExt.sort();ua=a.maxUploadSize;Pa=a.maxUploadFileSize;aa=a.saveInfCookie;l=parseInt(a.sortType);p=parseInt(a.sortOrder);Qa=a.maxFileNameLen;va=!!a.enableBrowseSubdir;M=!!a.enableFileOperation;ja=!!a.enableCreateDir;wa=!!a.enableRename;xa=!!a.enableDelete;ka=a.thmbPath||a.uploadPath;T=a.thmbDir;ya=a.tooltipsDelay;Ra=a.overlayOpacity;Sa=a.tooltipOverlayOpacity;Ta=a.dbclickDelay;la=a.onSelect;z=a.onDblSelect;ba=a.onDeselect;q=a.viewType;E=E.lastIndexOf("/")==
E.length-1?E.substring(0,E.length-1):E;l=l==3?3:l==2?2:1;p=p!=0?1:0;Y&&Y.length>0&&Y!=="default"&&(u=u+(u.indexOf("?")!=-1?"&":"?")+"setConfig="+Y);c=a.messages;j=[{text:c.select,handle:function(){z(H(e.index))},show:function(a){return z&&a.type==2},defaultItem:1,hotkeyText:w?"Enter":""},{text:c.selectThmb,handle:function(){var a=H(e.index);a.path=a.thmbPath;z(a)},show:function(a){return z&&a.type==2&&H(a.index).thmbPath},hotkeyText:w?"Shift + Enter":""},{text:c.open,handle:Ua,show:function(a){return a.type==
2},hotkeyText:w?"Ctrl + Enter":""},{text:c.browse,handle:lb,cssClass:"folder",show:function(a){return a.type==1&&va},defaultItem:1},{text:c.newDir,handle:za,cssClass:"newFolder",show:function(a,b,d){return!d&&ja},disabled:function(a,b,d,c){return!c},defaultItem:1,hotkeyText:w?"F7":""},{},{text:c.copy,handle:function(){ma(!1)},cssClass:"copy",show:function(){return M},disabled:function(a,b,d){return!d},hotkeyText:w?"Ctrl + C":""},{text:c.cut,handle:function(){ma(!0)},cssClass:"cut",show:function(){return M},
disabled:function(a,b,d,c){return!(d&&c)},hotkeyText:w?"Ctrl + X":""},{text:c.paste,handle:Va,cssClass:"paste",show:function(){return M},disabled:function(a,b){return!b},hotkeyText:w?"Ctrl + V":""},{text:c.del,handle:Wa,cssClass:function(){return e.type==1?"delFolder":"del"},show:function(){return xa},disabled:function(a,b,d,c){return!(d&&c)},hotkeyText:w?"Del":""},{text:c.rename,handle:Xa,cssClass:"rename",show:function(){return wa},disabled:function(a,b,d,c){return!(d&&c)},hotkeyText:w?"F2":""}];
if(a.contextMenuItems instanceof Array&&a.contextMenuItems.length>0){for(b in a.contextMenuItems)a.contextMenuItems[b].custom=!0;j=j.concat(a.contextMenuItems)}}function Ya(){mb();$(sa)?t=$(sa):(t=createElement("div"),document.getElementsByTagName("body")[0].appendChild(t));addClass(t,"imgLib");F&&!Za&&addClass(t,"ie");t.innerHTML="";I=createElement("div",{className:"tulbar"});s=createElement("div",{className:"fileList"});t.appendChild(I);t.appendChild(s);addEvent(t,"click",na);addEvent(s,"click",
function(a){a=fixEvent(a);a.shiftKey?(Aa(a),cancelEvent(a)):$a(a)});addEvent(s,"mouseover",nb);addEvent(s,"mousemove",ab);addEvent(s,"mouseout",N);addEvent(s,"contextmenu",Aa);Za&&addEvent(s,"mousedown",function(a){a.which==3&&Aa(a)});addEvent(window,"resize",bb);cb&&(n=createElement("div",{className:"droptarget",innerHTML:c.dropTargetText}),t.appendChild(n),addClass(n,"hide"),addEvent(window,"dragenter",function(a){cancelEvent(a);ca&&da?remClass(n,"hide"):(a=a.dataTransfer)&&(oa(a.types)?remClass(n,
"hide"):addClass(n,"hide"))}),addEvent(window,"dragleave",function(a){(a.pageX<=0||a.pageY<=0)&&addClass(n,"hide")}),addEvent(window,"dragover",function(a){cancelEvent(a);if(!ca||!da)if(a=a.dataTransfer)a.dropEffect="none"}),ca&&da&&addEvent(document,"drop",function(a){cancelEvent(a);addClass(n,"hide")}),addEvent(n,"dragenter",function(a){cancelEvent(a);ca&&da?addClass(n,"hover"):(a=a.dataTransfer)&&oa(a.types)&&addClass(n,"hover")}),addEvent(n,"dragleave",function(a){cancelEvent(a);remClass(n,"hover");
(a.pageX<=0||a.pageY<=0)&&addClass(n,"hide")}),addEvent(n,"dragover",function(a){cancelEvent(a);if((!ca||!da)&&ob)(a=a.dataTransfer)&&oa(a.types)}),addEvent(n,"drop",function(a){addClass(n,"hide");cancelEvent(a);if((a=a.dataTransfer)&&oa(a.types)&&a.files)db(a.files),O||ea(),J()}));w&&addEvent(document,"keydown",function(a){a=fixEvent(a);if(a.keyCode==113&&wa)Xa();else if(a.keyCode==118&&ja)za();else if(a.keyCode==45&&ta)ea();else if(a.ctrlKey)a.keyCode==88&&M?ma(!0):a.keyCode==67&&M?ma():a.keyCode==
86&&M?Va():a.keyCode==13&&Ua();else if(a.keyCode==46&&xa)Wa();else if(a.keyCode==13&&z&&e.type==2)a.shiftKey&&H(e.index).thmbPath?(a=H(e.index),a.path=a.thmbPath,z(a)):z(H(e.index))});ia&&("onhashchange"in window?addEvent(window,"hashchange",Ba):setInterval(Ba,Na*1E3));x(i);Ca=!0}function Aa(a){if(!O){G||(G=createElement("div",{className:"contextMenu"}),t.appendChild(G));N();G.innerHTML="";e=Da(a);e.type==2&&Ea(e.index);var b=e.type==1||e.type==2?!0:!1,h=A&&e.type!=2&&(!b&&m.inf.isWritable||e.type==
1)?!0:!1,c=createElement("ul"),d,o,f;d=0;for(o=j.length;d<o;d++)if(("show"in j[d]&&typeof j[d].show=="function"?j[d].show(e,h,b,m.inf.isWritable):j[d].show)||!("show"in j[d]))!f&&j[d].custom&&(f=1,c.appendChild(K())),c.appendChild(K(j[d].text,j[d].handle,j[d].cssClass,"disabled"in j[d]?typeof j[d].disabled=="function"?j[d].disabled(e,h,b,m.inf.isWritable):!!j[d].disabled:!1,j[d].defaultItem,j[d].hotkeyText));G.appendChild(c);G.style.display="block";eb(a,G,0);cancelEvent(a)}}function na(){if(G)G.style.display=
"none"}function K(a,b,h,c,d,o){var f=createElement("li",{className:(c?" disabled":"")+(d?" default":"")}),h=createElement("div",{className:"icon "+(typeof h=="function"?h():h||"")}),d=createElement("div",{innerHTML:a,className:"name"}),e=createElement("span",{innerHTML:o,className:"hotkey"});a?(F&&(addEvent(f,"mouseover",function(){addClass(f,"hover")}),addEvent(f,"mouseout",function(){remClass(f,"hover")})),!c&&b&&addEvent(f,"click",function(a){na();b(a)}),f.appendChild(h),f.appendChild(d),o&&f.appendChild(e)):
f.className="separator";return f}function Da(a){var a=fixEvent(a).target,b,h,c;if(a.nodeType==3)a=a.parentNode;for(;a&&a.parentNode&&!("index"in a);)a=a.parentNode;"index"in a?(b=a.itemType,h=a.index,c=b==1?h>=0?m.dirs[h].name:"":b==2?m.files[h].name:""):b=-1;return{type:b,index:h,name:c,time:(new Date).getTime(),target:a}}function H(a){if(m.files[a]){a=extend({},m.files[a]);a.localPath="/"+(m.path.length>0?m.path.join("/")+"/":"")+a.name;a.path=getURIEncPath(HTMLDecode(E+i+a.name));a.humanSize=getHumanSize(a.filesize,
c.fileSizeDim);if(a.thmb&&a.thmb!=="")a.thmbPath=getURIEncPath(HTMLDecode(ka+i+T+"/"+a.thmb));return a}}function Xa(){if(!m.inf.isWritable)return alert(c.writeProtect);var a=HTMLDecode(e.name),b,h;if(a&&a!=""&&(e.type==2&&(a=a.split("."),b=a.pop(),a=a.join(".")),h=prompt(sprintf(c.enterNewNameWOExt,HTMLDecode(e.name)),a)))h!=a?(e.type==2&&(h=h+"."+b),U(),sendXMLHttpReq(u,{mode:"POST",parameters:"cmd=rename&src="+encodeURIComponent(i+e.name)+"&new_name="+encodeURIComponent(h),onsuccess:function(a){P();
a=JSON.parse(a.responseText).result;a!=0&&alert(sprintf(c.operationFailed,a));x(i)}})):alert(c.noChange)}function Wa(){if(!m.inf.isWritable)return alert(c.writeProtect);var a=HTMLDecode(e.name),b=sprintf(e.type==1&&m.dirs[e.index].empty=="0"?c.delNonEmptyDir:c.delFile,a);a&&a!=""&&confirm(b)&&(U(),sendXMLHttpReq(u,{mode:"POST",parameters:"cmd=rm&dst="+encodeURIComponent(i+a)+"&rec=1",onsuccess:function(a){P();a=JSON.parse(a.responseText).result;a!=0&&alert(sprintf(c.operationFailed,a));x(i)}}))}function za(){if(!m.inf.isWritable)return alert(c.writeProtect);
var a=prompt(c.enterNewDirName,c.defaultNewDirName);a&&(U(),sendXMLHttpReq(u,{mode:"POST",parameters:"cmd=mkdir&dst="+encodeURIComponent(i)+"&name="+encodeURIComponent(a),onsuccess:function(a){P();a=JSON.parse(a.responseText).result;a!=0&&alert(sprintf(c.operationFailed,a));x(i)}}))}function $a(a){var b={};e&&e.type==2&&(b=e);e=Da(a);if(e.type==1&&va)e.index>=0?x(i+e.name+"/"):(b=m.path.length+e.index+1,x("/"+(b>0?m.path.slice(0,b).join("/")+"/":"")));else if(e.type==2){if(Ea(e.index),la||z)a=H(e.index),
la&&la(a),z&&b.index==e.index&&e.time-b.time<Ta&&z(a)}else Ea(),N(),ba&&ba()}function lb(){e.type==1&&x(i+e.name+"/")}function Ua(){e.type==2&&window.open(getURIEncPath(HTMLDecode(E+i+e.name)),"_blank")}function ma(a){if(e.type==1||e.type==2)A={cmd:a&&m.inf.isWritable?"move":"copy",name:i+e.name},Fa()}function Va(){if(A){if(!m.inf.isWritable)return alert(c.writeProtect);U();sendXMLHttpReq(u,{mode:"POST",parameters:"cmd="+A.cmd+"&src="+encodeURIComponent(A.name)+"&dst="+encodeURIComponent(i+(e.type==
1?e.name:"")),onsuccess:function(a){P();a=JSON.parse(a.responseText).result;a!=0&&alert(sprintf(c.operationFailed,a));A=null;Fa();x(i)}})}}function Fa(){var a=[encodeURIComponent(i),encodeURIComponent(q),l,p,A?encodeURIComponent([encodeURIComponent(A.cmd),encodeURIComponent(A.name)].join(",")):""].join();pa?(Z?localStorage:sessionStorage).setItem(aa,a):Z&&setCookie(aa,a);if(ia)a=getURLArg().hash,a.path=encodeURI(i),setLocationHash(a)}function mb(){var a;pa?a=(Z?localStorage:sessionStorage).getItem(aa):
Z&&(a=getCookie(aa));ia&&Ba(0,1);a&&a.length>0&&(a=a.split(","),a[0].length>0&&a[0]!="/"&&(i=decodeURIComponent(a[0])),q=decodeURIComponent(a[1]),l=parseInt(a[2]),p=parseInt(a[3]),!A&&a[4]&&(a=decodeURIComponent(a[4]).split(","),A={cmd:decodeURIComponent(a[0]),name:decodeURIComponent(a[1])}))}function Ba(a,b){var c=getURLArg().hash.path;if(c&&c.length>0&&(c=decodeURI(c),c!==i))b?i=c:x(c)}function x(a){U();e={};a=HTMLDecode(a||i);sendXMLHttpReq(u+(u.indexOf("?")!=-1?"&":"?")+"cmd=list&src="+encodeURIComponent(a),
{mode:"GET",onsuccess:function(a){m=JSON.parse(a.responseText.substr(9));B();P()}})}function fb(){x(i)}function B(){var a=m.path,b=1,h=createElement("div",{className:"folderTree"}),g=createElement("div",{className:"box"}),d=m.dirs,o=m.files,f=createElement("div",{className:"controls"}),e=createElement("div",{className:"label curent"}),k=createElement("div",{className:"icon openFolder"}),L=createElement("div",{className:"icon dropDown"}),j=createElement("span"),n=createElement("ul",{className:"tree"}),
Ga,t=createElement("div",{className:"contextMenu"}),u=createElement("div",{className:"contextMenu"}),v=createElement("div",{className:"searchBox",innerHTML:c.enterSearch}),r=createElement("input",{type:"text"});i="/";I.style.display="none";s.style.display="none";I.innerHTML="";V=!1;addEvent(e,"click",function(){na();N();V?remClass(h,"expanded"):addClass(h,"expanded");V=!V});addEvent(h,"mouseover",function(){clearTimeout(gb);N()});addEvent(h,"mouseout",function(){gb=setTimeout(function(){remClass(h,
"expanded");V=!V},ya)});a.length==0?(j.innerHTML=c.rootPathName,e.title="/"):(j.innerHTML=Q(a[a.length-1]),e.title=HTMLDecode(a[a.length-1]));e.appendChild(k);e.appendChild(j);e.appendChild(L);addEvent(n,"click",function(a){$a(a)});if(a.length>0){k=0;for(L=a.length;k<L;k++)k==L-1&&(Ga=R(c.moveToUpDir,function(a){return function(){return x(a)}}(i),"upFolder")),i+=a[k]+"/",k==0&&n.appendChild(Ha(c.rootPathName,"/",-(L+1),"openFolder",0)),n.appendChild(Ha(Q(a[k]),a[k],k-L,"openFolder"+(k==L-1?" curent":
""),b++,k==L-1?" curent":""))}i=HTMLDecode(i);d=d.sort(function(a,b){return l==3?a.date-b.date:a.name>b.name?1:a.name<b.name?-1:0});o=o.sort(function(a,b){return l==2?a.filesize-b.filesize:l==3?a.date-b.date:a.name>b.name?1:a.name<b.name?-1:0});p&&(d.reverse(),o.reverse());for(k=0;k<d.length;k++)d[k].name!=T&&n.appendChild(Ha(Q(d[k].name),d[k].name,k,d[k].empty==0?"full":"",b));g.appendChild(e);g.appendChild(n);h.appendChild(g);Ga&&f.appendChild(Ga);f.appendChild(R(c.reloadDir,fb,"reload"));a=createElement("ul");
a.appendChild(K(c.thumbnail,function(){q="thumbnail";B()},"viewThumbnail",0,q=="thumbnail"));a.appendChild(K(c.list,function(){q="list";B()},"viewList",0,q=="list"));a.appendChild(K(c.table,function(){q="table";B()},"viewTable",0,q=="table"));t.appendChild(a);f.appendChild(R(c.view,!1,"view",t));a=createElement("ul");a.appendChild(K(c.sortByName,function(){p=l==1?W(p-1):0;l=1;B()},"sort "+(l==1?p?"asc":"desc":"asc"),0,l==1));a.appendChild(K(c.sortBySize,function(){p=l==2?W(p-1):0;l=2;B()},"sort "+
(l==2?p?"asc":"desc":"asc"),0,l==2));a.appendChild(K(c.sortByDate,function(){p=l==3?W(p-1):0;l=3;B()},"sort "+(l==3?p?"asc":"desc":"asc"),0,l==3));u.appendChild(a);f.appendChild(R(c.sort,!1,"sort",u));addEvent(r,"keyup",function(){hb(r.value)});addEvent(r,"keypress",function(){hb(r.value)});v.appendChild(r);f.appendChild(R(c.search,!1,"search",v));ja&&f.appendChild(R(c.newDir,za,"newFolder"));ta&&f.appendChild(R(c.upload+(w?"&nbsp;(Insert)":""),ea,"upload"));qa();I.appendChild(h);I.appendChild(f);
I.style.display="";s.style.display="";bb();Fa()}function qa(a){var a=a||m,b=a.dirs,a=a.files,h,g=q!="table"?createElement("ul"):createElement("table"),d,o;s.innerHTML="";g.className=q;ba&&ba();N();if(q=="table"){var f=createElement("tr",{className:"title"});h=createElement("th",{innerHTML:c.fileName});o=createElement("th",{innerHTML:c.size});var e=createElement("th",{innerHTML:c.date}),k=createElement("colgroup"),j;d=createElement("div",{className:"icon sort "+(p?"desc":"asc")});addEvent(h,"click",
function(a){p=l==1?W(p-1):0;l=1;B();cancelEvent(a)});addEvent(o,"click",function(a){p=l==2?W(p-1):0;l=2;B();cancelEvent(a)});addEvent(e,"click",function(a){p=l==3?W(p-1):0;l=3;B();cancelEvent(a)});l==3?e.appendChild(d):l==2?o.appendChild(d):h.appendChild(d);for(d=1;d<4;d++){j=createElement("col");if(d==l)j.className="sorted";k.appendChild(j)}g.appendChild(k);g.appendChild(createElement("tbody"));f.appendChild(h);f.appendChild(o);f.appendChild(e);g.lastChild.appendChild(f)}for(d=0;d<b.length;d++)if(b[d]&&
(h=b[d].name,h!=T))o=Q(h),f=q=="table"?createElement("tr"):createElement("li"),k=createElement("div",{className:"icon folder"+(b[d].empty==0?" full":"")}),f.title=HTMLDecode(h),F&&(addEvent(f,"mouseover",function(a){return function(){addClass(a,"hover")}}(f)),addEvent(f,"mouseout",function(a){return function(){remClass(a,"hover")}}(f))),q=="thumbnail"?(f.innerHTML='<div class="image"></div><div class="name">'+o+"</div>",f.firstChild.appendChild(k)):q=="table"?(j=createElement("span",{innerHTML:o}),
h=createElement("td"),o=createElement("td"),e=createElement("td",{innerHTML:getDateF(b[d].date*1E3,1)}),h.appendChild(k),h.appendChild(j),f.appendChild(h),f.appendChild(o),f.appendChild(e)):(f.innerHTML+=o,f.insertBefore(k,f.firstChild)),f.index=d,f.itemType=1,q=="table"?g.lastChild.appendChild(f):g.appendChild(f);if(a.length>0)for(d=0;d<a.length;d++)if(a[d])h=a[d].name,b=h.substring(h.lastIndexOf(".")+1).toLowerCase(),f=q=="table"?createElement("tr"):createElement("li"),k=createElement("div",{className:"icon files "+
b,style:{styleFloat:"left"}}),o=Q(h),F&&(addEvent(f,"mouseover",function(a){return function(){addClass(a,"hover")}}(f)),addEvent(f,"mouseout",function(a){return function(){remClass(a,"hover")}}(f))),q=="thumbnail"?(f.innerHTML+=sprintf('<div class="image">%1</div><div class="name">%2</div>',a[d].thmb&&a[d].thmb!=""?sprintf('<img class="loading" src="%1" alt="" />',getURIEncPath(HTMLDecode(ka+i+T+"/"+a[d].thmb)),o):"",o),(!a[d].thmb||a[d].thmb=="")&&f.firstChild.appendChild(k)):q=="table"?(j=createElement("span",
{innerHTML:o}),h=createElement("td"),o=createElement("td",{innerHTML:getHumanSize(a[d].filesize,c.fileSizeDim)+(a[d].img_size?" ("+a[d].img_size+")":"")}),e=createElement("td",{innerHTML:getDateF(a[d].date*1E3,1)}),h.appendChild(k),h.appendChild(j),f.appendChild(h),f.appendChild(o),f.appendChild(e)):(f.innerHTML+=o,f.insertBefore(k,f.firstChild)),f.index=d,f.itemType=2,q=="table"?g.lastChild.appendChild(f):g.appendChild(f);s.appendChild(g)}function R(a,b,c,g){var d=createElement("div",{className:"btn",
title:HTMLDecode(a)}),a=createElement("div",{className:"icon "+c});typeof b=="function"&&addEvent(d,"click",function(a){b(a)});F&&(addEvent(d,"mouseover",function(){addClass(d,"hover")}),addEvent(d,"mouseout",function(){remClass(d,"hover")}));g&&d.appendChild(g);d.appendChild(a);return d}function Ha(a,b,c,g,d,e){var f=createElement("li",{className:e||"",title:HTMLDecode(b),index:c,itemType:1}),b=createElement("div",{className:"icon folder "+g,style:{marginLeft:d+"em"}}),a=createElement("span",{innerHTML:a});
F&&(addEvent(f,"mouseover",function(){addClass(f,"hover")}),addEvent(f,"mouseout",function(){remClass(f,"hover")}));f.appendChild(b);f.appendChild(a);return f}function Q(a,b){b=b||Qa;if(a.length>b)var a=a.split("."),c=a.pop(),a=b-c.length>5?a.join(".").substring(0,b-c.length-3)+"..."+c:(a.join(".")+"."+c).substring(0,b-3)+"...";return a}function U(a){if(!C){C=createElement("div",{className:"ajaxLoad"});var b=createElement("div",{className:"overlay"}),h=createElement("div",{className:"loadIcon",innerHTML:c.ajaxLoading});
C.appendChild(b);C.appendChild(h);t.appendChild(C);setTransparency(b,Ra)}a?addClass(C,"noBlock"):remClass(C,"noBlock");remClass(C,"hide")}function P(){C&&addClass(C,"hide")}function nb(a){a=fixEvent(a);ib=setTimeout(function(){var b=Da(a);fa=b.type==2?b.index:-1;ab(a)},ya)}function ab(a){v||(v=createElement("div",{className:"tooltips"}),t.appendChild(v));if(v.tII!==fa){var b=m.files[fa],h=createElement("div",{className:"overlay"});if(!b)return;v.tII=fa;v.style.display="";v.innerHTML="";v.appendChild(h);
setTransparency(h,Sa);v.appendChild(createElement("span",{className:"body",innerHTML:(b.thmb&&b.thmb!==""&&q!="thumbnail"?sprintf('<img class="loading" src="%1" alt="%2" />',getURIEncPath(HTMLDecode(ka+i+T+"/"+b.thmb)),b.name):"")+sprintf("<span>%1: %2<br />%3: %4<br />%5: %6 %7</span>",c.fileName,b.name,c.fileSize,getHumanSize(b.filesize,c.fileSizeDim),c.fileDate,getDateF(b.date*1E3,1),b.img_size?"<br />"+c.imageSize+": "+b.img_size:"")}))}eb(a,v)}function N(){clearTimeout(ib);fa=-1;if(v)v.tII=-1,
v.style.display="none"}function eb(a,b,c){var g=fixEvent(a),a=getWindowGeometry(),d=g.pageX,g=g.pageY,e=0,f=0;typeof c=="undefined"&&(c=20);f=d+b.offsetWidth+c-a.xOffset>a.width?d-b.offsetWidth-c:d;e=g+b.offsetHeight+c-a.yOffset>a.height?g-b.offsetHeight-c:g;b.style.top=e+c+"px";b.style.left=f+c+"px"}function bb(){var a=getElPos(t),b,a=a.height-2;if(a>0)b=getElPos(I),b=b.height,F&&b++,s.style.height=a-b+"px"}function Ea(a){var b=s.getElementsByTagName(q!="table"?"li":"tr"),c;for(c=b.length;c-- >0;)remClass(b[c],
"selected"),typeof a!="undefined"&&b[c].itemType==2&&b[c].index==a&&addClass(b[c],"selected")}function hb(a){var b={dirs:[],files:[]},c=m.dirs,g=m.files,d;if(a.length>0){for(d=0;d<c.length;d++)c[d].name.toLowerCase().indexOf(a.toLowerCase())!=-1&&(b.dirs[d]=c[d]);for(d=0;d<g.length;d++)g[d].name.toLowerCase().indexOf(a.toLowerCase())!=-1&&(b.files[d]=g[d]);qa(b)}else qa()}function ea(){if(!m.inf.isWritable)return alert(c.writeProtect);if(O){O=!O;if(Ia&&Ja){for(var a=r.length;a-- >0;)r[a].state==2&&
r[a].xhr.abort();r=[]}P();return ga?fb():qa()}else{O=!O;ha=ga=!1;na();N();var a=createElement("div",{className:"uploadBox"}),b=createElement("div",{className:"info",innerHTML:"<div>"+[sprintf(c.allowExt,Oa.join(", ")),sprintf(c.maxUploadSize,getHumanSize(ua,c.fileSizeDim),getHumanSize(Pa,c.fileSizeDim)),pb?c.multipleUpload:"",cb?c.dragAndDropSupport:"",sprintf(c.path,"/"+(m.path.length>0?m.path.join("/")+"/":""))].join("</div><div>")+"</div>"}),h=createElement("button",{innerHTML:'<div class="icon upload"></div><span class="text">'+
c.upload+"</span>",className:"gren_btn"}),g=createElement("button",{innerHTML:'<div class="icon del"></div><span class="text">'+c.close+"</span>",className:"red_btn"}),d=createElement("div",{className:"icon add",title:HTMLDecode(c.addField)}),e=createElement("div"),f=createElement("input",{type:"checkbox",id:"auto_close_form",defaultChecked:Ka}),i=createElement("label",{innerHTML:c.autoCloseForm,htmlFor:"auto_close_form"});D=createElement("div",{className:"inputs"});addEvent(f,"click",function(){Ka=
f.checked;ha=!1});D.appendChild(La());addEvent(d,"click",function(){D.appendChild(La(1))});addEvent(g,"click",function(){ea()});addEvent(h,"click",function(){h.disabled=!0;h.className="gray_btn";J()});s.innerHTML="";e.appendChild(f);e.appendChild(i);a.appendChild(b);a.appendChild(D);a.appendChild(e);a.appendChild(h);a.appendChild(g);a.appendChild(d);a.appendChild(createElement("div",{className:"clear"}));s.appendChild(a)}}function La(a){var b=createElement("form",{method:"post",action:u,enctype:"multipart/form-data",
encoding:"multipart/form-data",innerHTML:sprintf('<input type="hidden" name="MAX_FILE_SIZE" value="%1" /><input type="hidden" name="dir" value="%2" /><label>%3:</label><input type="file" name="file[]" multiple />',ua,encodeURIComponent(i),c.fileName)}),h=createElement("div",{className:"input"}),g=createElement("div",{className:"icon del",title:HTMLDecode(c.delField)}),d=createElement("div",{className:"clear"});addEvent(g,"click",function(){h.parentNode.removeChild(h)});h.appendChild(b);a&&h.appendChild(g);
h.appendChild(d);return h}function J(a){if(m.inf.isWritable){var b=D.getElementsByTagName("form"),h,g;if(!a){for(g=b.length;g-- >0;)b[g]["file[]"].value==""&&D.removeChild(b[g].parentNode);U(1)}b=D.getElementsByTagName("form");if(Ia&&Ja){for(g=b.length;g-- >0;)db(b[g]["file[]"].files),D.removeChild(b[g].parentNode);var d;for(g=0;g<r.length;g++)if(d=r[g],d.state==0){var e=d.file,f=createElement("div",{className:"progress"}),i=createElement("div",{className:"indicator"}),k=createElement("div",{className:"label"}),
j=createElement("span",{className:"link"}),l=createElement("div",{className:"clear"});d.name=e.name||e.fileName;d.size=e.size||e.fileSize;d.type=e.type||c.unknownMime;e=createElement("div",{className:"input",innerHTML:sprintf('<span class="hint">%1 (%2)</span>',Q(d.name),getHumanSize(d.size,c.fileSizeDim)),title:d.name+" ("+c.fileType+d.type+")"});d.size==0?r.splice(g,1):(f.appendChild(i),f.appendChild(k),e.insertBefore(f,e.firstChild),e.appendChild(j),addEvent(j,"click",function(a){return function(){if(a.state==
1)a.state=5,y(a);else if(a.state==2)a.xhr.abort(),a.state=6,X=!1,y(a),J(1);else if(a.state!=3&&a.state==4)a.state=1,y(a),J(1)}}(d)),e.appendChild(l),d.indicatorBox=f,d.mainContainer=e,d.controllLink=j,d.indicator=i,d.indicatorLabel=k,d.state=1,y(d),D.appendChild(e))}else if(d.state>4)r.splice(g,1);else if(d.state==3)d.file=d.uploadEvent=d.xhr=void 0;if(!X){for(g=0;g<r.length;g++)if(r[g].state==1){qb(r[g]);break}g==r.length&&(h=!0)}}else if(b.length>0){b=b[0];addClass(b.parentNode,"active");g="if"+
Math.floor(Math.random()*1E9);d=createElement("span",{innerHTML:'<iframe style="display:none;" name="'+g+'" id="'+g+'" src=""></iframe>'});var n;b.setAttribute("target",g);s.appendChild(d);n=$(g);addEvent(n,"load",function(){var a=n.contentDocument||n.contentWindow.document||window.frames[n.id].document,d=b.parentNode,e;if(a&&a.location.href!=""){try{var a=JSON.parse(a.body.innerText||a.body.textContent),f=[],g;for(g in a.results)a.results[g][0]?(g=a.results[g][1],f.push(c.error+(c["ec"+g]||g)),e=
!0):f.push(a.results[g][1]);d.innerHTML=sprintf(c.uploadResult,a.count,f.join(", "));a.count>0&&(ga=!0)}catch(h){d.innerHTML=sprintf(c.operationFailed,h),e=!0}e?(addClass(d,"error"),ha=!0):addClass(d,"success");remClass(d,"active");J(1)}});b.submit()}else h=!0;h&&(D.appendChild(La()),extend(s.getElementsByTagName("button")[0],{disabled:!1,className:"gren_btn"}),P(),a?Ka&&ga&&!ha&&ea():alert(c.noFileSelected))}}function db(a){for(var b=0;b<a.length;b++)r.push({state:0,file:a[b]})}function y(a){var b=
a.state,e=a.indicator,g=a.indicatorLabel,d=a.controllLink;if(b==1)e.style.width="0%",g.innerHTML=g.title=c.waitInQueue,d.innerHTML=c.cancel;else if(b==2){if(d.innerHTML!=c.abort)d.innerHTML=c.abort;var i=a.uploadEvent;if(i.lengthComputable){var f=i.loaded/i.total*100,j=i.loaded/((new Date).getTime()-a.startTime)*1E3,i=jb((i.total-i.loaded)/j);e.style.width=f+"%";g.innerHTML=g.title=jb(f)+"% | "+c.speed+": "+getHumanSize(j,c.fileSizeDim)+c.speedUnit+" | "+c.timeLeft+": "+i+c.second}}else if(b==3)e=
(a.endTime-a.startTime)/1E3,j=a.size/e,g.innerHTML=g.title=getHumanSize(a.response[1],c.fileSizeDim)+" | "+c.speed+": "+getHumanSize(j,c.fileSizeDim)+c.speedUnit+" | "+c.time+": "+e+c.second,extend(d,{innerHTML:sprintf(c.savedAs,Q(a.response[2])),title:a.response[2],className:"hint"});else if(b==4)d.innerHTML=c.tryAgain,g.innerHTML=g.title=a.errorMsg||c.error;else if(b==5)g.innerHTML=c.canceled;else if(b==6)g.innerHTML=c.aborted;else if(b==7)g.innerHTML=g.title=a.errorMsg||c.error;b>4&&(addClass(d,
"hide"),setTimeout(function(){addClass(a.mainContainer,"hide")},3E3));d.appendChild(createElement("div",{className:b<3?"icon del":b==4?"icon reload":""}));a.indicatorBox.className="progress"+(b==3?" done":b>3?" error":"")}function qb(a){X=!0;a.state=2;try{var b=getXHR();addEvent(b.upload,"progress",function(b){a.uploadEvent=b;y(a)});addEvent(b,"load",function(){if(b.status==200||b.status==304)try{var e=JSON.parse(b.responseText),d=e[0];d==0?e[1]==a.size?(a.state=3,a.response=e,a.endTime=(new Date).getTime(),
y(a),ga=!0):(a.state=4,a.errorMsg=c.sizeNotMatch,y(a)):(a.errorMsg=c.errorUpload+": "+(c["ec"+d]||d),a.state=d!=503?7:4,y(a))}catch(h){a.state=4,a.errorMsg=c.errorOnResponse+h.toString()+" -- "+b.responseText,y(a)}else a.state=4,a.errorMsg=c.errorOnResponse+b.status+" "+b.statusText,y(a);if(a.state==4||a.state==7)ha=!0;X=!1;J(1)});addEvent(b,"error",function(){a.state=4;a.errorMsg=c.errorUpload;y(a);X=!1;J(1)});b.open("POST",u+(u.indexOf("?")!=-1?"&":"?")+"upload&name="+encodeURIComponent(a.name)+
"&dir="+encodeURIComponent(i));a.startTime=(new Date).getTime();a.xhr=b;b.send(a.file)}catch(e){a.state=4,a.errorMsg=c.errorEx+e.toString(),y(a),X=!1,J(1)}}function oa(a){return a.contains&&a.contains("Files")||a.indexOf&&a.indexOf("Files")!=-1?!0:!1}var S=navigator.userAgent.toLowerCase(),ca=S.indexOf("linux")!=-1?1:0,F=(F=S.indexOf("msie"))!=-1&&parseInt(S.substr(F+5,1))<8?1:0,da=S.indexOf("firefox")!=-1?1:0,Za=window.opera?1:0,ob=S.indexOf("webkit")!=-1?1:0,pb="multiple"in createElement("input"),
pa;try{pa="sessionStorage"in window&&window.sessionStorage!==null}catch(rb){pa=!1}var S="draggable"in createElement("span"),Ia="upload"in getXHR(),Ja=typeof FileReader!="undefined",cb=S&&Ia&&Ja?1:0,r=[],X=!1,e,A,gb,ib,O,ga,ha,Ka=!0,Ca=!1,V,fa,i="/",m={},sa,u,Y,Ma,w,ia,Na,Z,ta,E,Oa,ua,Pa,aa,l,p,Qa,va,M,ja,wa,xa,ka,T,ya,Ra,Sa,Ta,la,z,ba,q,c={},j,t,C,G,I,s,D,v,n,W=Math.abs,jb=Math.round,ra={};return{init:function(a){kb(a);if(!getXHR())return alert(c.ajaxIsReguire),!1;Ma?Ya():addEvent(window,"load",Ya)},
getSelectedItem:function(){if(e)return e},getItemInfo:function(a,b){if(a==1)return m.dirs[b];else if(a==2)return H(b)},getDirContent:function(){return m},gotoPath:function(a){Ca&&x(a)},setStartPath:function(a){Ca||(i=a)},getConfig:function(a){return a?ra[a]:ra}}}();